### ISSUE TITLE
Android SDK successfully connects to watch but doesn't receive data

### ISSUE THREAD

**Issue by athul326** [analogdevicesinc/study-watch-sdk#3]
I am trying to use the Android SDK to retrieve battery life data from the watch however after the SDK successfully connects to the watch, I receive an error saying that no data is received. Any help would be appreciated.

Here is the code snippet of the SDK connection and the method used to get battery life:
```
StudyWatch.connectBLE("EB:81:4E:95:53:06", applicationContext, object : StudyWatchCallback {
                    override fun onSuccess(sdk: SDK) {
                        Log.d("Connection", "onSuccess: SDK Ready")
                        watchSdk = sdk // store this sdk reference to be used for creating applications
                        readBatter()
                        // Get EDA application from SDK
                    }
                    override fun onFailure(message: String, state: Int) {
                        Log.d("Connection", "onError: $message")
                    }
                })
private fun readBatter(){
    val pmApp = watchSdk!!.pmApplication
    val battInfo = pmApp.batteryInfo.payload.batteryLevel
    Log.w("Battery", "Battery Info: $battInfo")
}
```
![image](https://user-images.githubusercontent.com/35794954/114326927-a5430100-9afc-11eb-9a7d-02a3fca10bb6.png)
Logs returned after running my code

**Comment by anoop-adi** [comment]
Hi Athul,

we have released a new version, and you can get more info about that here:
https://github.com/analogdevicesinc/study-watch-sdk/tree/main/android

There are few examples here: 
https://github.com/analogdevicesinc/study-watch-sdk/tree/main/android/AndroidSamples

Now coming to your issue, you need to run it on the UI thread.

Call readBatter function on UI thread.

`runOnUiThread { readBatter() }`

Or alternately, you can use button click events, and there is also an example of running these commands as ExecutorService.

Regards,
Anoop
